[Feature] Add `docker compose-dev.yml` for development
COSCUP/subscribe pull request #5
Opened 2023-09-09 15:27 UTC by orertrr

## 內容

新增 docker-compose-dev.yml 以建立開發環境

## 相關 issue

- #3 

## 建立流程

**Build Base Image**

```
sudo docker build -t secretaryweb-base:23.09.01 -f ./Dockerfile-base-dev ./
```

**Set setting.py**

```
cp setting_example.py setting.py
```

**Setup**

```
sudo docker compose -f ./docker-compose-dev.yml up -d
```

開啟瀏覽器並輸入 http://localhost/ 即可進入測試網站

2023-09-26 14:53 UTC, toomore requested changes
再幫忙調整一下，感謝！

2023-09-26 14:53 UTC, toomore commented on Dockerfile-base-dev
> +        cd ../ && rm -rf ./jemalloc* && \
測試環境不用裝 `jemalloc` 會比較快。

2023-09-26 14:53 UTC, toomore commented on Dockerfile-base-dev
> +FROM alpine:3.18.3
這個改用 `FROM python:3.11.4-alpine3.18`，`Dockerfile-base` 底下的也幫我改用這個。

2023-09-26 14:53 UTC, toomore commented on nginx/Dockerfile
> +FROM nginx:1.25.1-alpine
有新版的，改用 `nginx:1.25.2-alpine`

2023-09-26 16:13 UTC, orertrr commented
沒問題，修改完了

2023-09-27 03:32 UTC, toomore approved these changes
看起來沒問題了！

2023-10-14 23:39 UTC, merged